table olist_customers_dataset
	lineageTag: 37d410bf-85ef-483d-bdea-11cda2733224

	measure 'Best Region' = TOPN(1,VALUES('Table'[state name]))
		lineageTag: 592ee81a-86af-486d-b272-11bd078ced03

	measure 'Total customers' = DISTINCTCOUNT(olist_customers_dataset[customer_id])
		formatString: 0
		lineageTag: 3a92d3c6-2caf-4c9c-af00-9a0a9e229981

	measure 'Best Region City' = TOPN(1,VALUES(olist_customers_dataset[customer_city]))
		lineageTag: f0a632f3-3107-460c-bd7e-fe3a4e4c6756

	measure 'BRS Count' = CALCULATE(DISTINCTCOUNT(olist_customers_dataset[customer_id]),olist_customers_dataset[customer_state]="SP")
		formatString: 0
		lineageTag: 30a344e7-fb48-43be-a0bf-2df1197201d6

	measure 'BRC Count' = CALCULATE(DISTINCTCOUNT(olist_customers_dataset[customer_id]),olist_customers_dataset[customer_city]="franca")
		formatString: 0
		lineageTag: 28ec04f5-75c2-44cc-88c6-7b7451356bae

	column customer_id
		dataType: string
		lineageTag: 800b976d-2e1f-449e-bb5f-6ec98ae7db91
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: b8f1f1ad-28b1-4df7-884b-22211a757580
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: f6bd12ad-58f6-4f2b-999b-42f2a0ab8091
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: cc36dd4e-8056-41d0-a447-74276bf3492d
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition olist_customers_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\My office\archive\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"customer_unique_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"customer_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

