table olist_geolocation_dataset
	lineageTag: ddbb690e-5e97-4567-b665-4c8e1a785c32

	column geolocation_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 91d9b99b-c708-4b76-bd81-8540b7ef1563
		summarizeBy: sum
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_lat
		dataType: double
		lineageTag: 3a89c110-83a3-42be-8fce-a3eef23246b7
		summarizeBy: sum
		sourceColumn: geolocation_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_lng
		dataType: double
		lineageTag: c7710673-6a31-499d-90c2-f1264b46388e
		summarizeBy: sum
		sourceColumn: geolocation_lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_city
		dataType: string
		lineageTag: 569f7afd-22f1-4f1a-acd6-079e5d6dc9d6
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: 402906dd-29bd-42e0-b99e-818dc73f949c
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	partition olist_geolocation_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\My office\archive\olist_geolocation_dataset.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"geolocation_zip_code_prefix", Int64.Type}, {"geolocation_lat", type number}, {"geolocation_lng", type number}, {"geolocation_city", type text}, {"geolocation_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

