table olist_order_reviews_dataset
	lineageTag: f7675135-7700-48da-874d-a981c27f1819

	measure 'Average Rating' = ```
			AVERAGE(olist_order_reviews_dataset[review_score]) 
			```
		lineageTag: e3701822-24d6-4327-ad0c-64680579ff63

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_id
		dataType: string
		lineageTag: 0762ccda-5ad1-4a78-9546-7e9a46ef5593
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 62b9689d-a641-4eb6-818d-56ebbb4cc200
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 1936a7ca-bf73-4dce-8352-10167d984550
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 5e11240d-acde-4e2f-82df-d0aeb67befe6
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 931604f9-f912-4cbf-abce-02a236f503f1
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 37fc382a-1e43-4dff-97d0-c3aa059936f6
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 5cf17989-2bbe-4a33-9d9f-b27d8abe647f
			defaultHierarchy: LocalDateTable_f0f48050-c579-4e07-9573-2a9a16e1e717.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 750f5365-77a8-46d7-85d1-4bfee2dad85f
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 29f924bf-f273-451d-8a9a-39beb46604fc
			defaultHierarchy: LocalDateTable_35f06404-3ca6-4d10-803b-e4eb3099ecfe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition olist_order_reviews_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\My office\archive\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

