table olist_orders_dataset
	lineageTag: 52d4b67a-2ad6-4e9d-bfad-5b527e1ffab4

	measure 'MoM Display' = IF([MoM %]>0,UNICHAR(9650)& " " & FORMAT([MoM %],"0.0%"),UNICHAR(9660) &" "& FORMAT(ABS([MoM %]),"0.0%"))
		lineageTag: aea1fc3d-eee9-4a5f-9786-7ceed1bb404a

	measure 'delivered Order' = CALCULATE(COUNT(olist_orders_dataset[order_id]),olist_orders_dataset[Order Status ]="completed")
		formatString: 0
		lineageTag: feacace7-5962-426a-817f-f69ea86abe81

	measure 'Order completed %' = DIVIDE(CALCULATE([delivered Order]),COUNT(olist_orders_dataset[order_id]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 04b9c9a6-16a2-4afa-8464-ca1484f6e6ac

	measure 'Cancel rate' = DIVIDE(CALCULATE(COUNTROWS(olist_orders_dataset),olist_orders_dataset[Order Status ]="canceled"),COUNTROWS(olist_orders_dataset))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 646f66ef-c609-4a37-a24f-597293523802

	column order_id
		dataType: string
		lineageTag: b81d9d40-4469-44d2-a801-43b862c1788b
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 75c131e4-48b2-4f0a-be49-acc6f7e91d42
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column 'order_status 1'
		dataType: string
		lineageTag: 7198b2f7-fa32-4bb3-a9bd-bcf5dd6a3397
		summarizeBy: none
		sourceColumn: order_status 1

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: Short Date
		lineageTag: 379511f2-8658-45f0-a66b-bd1ea40b500b
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: c1b3602e-705d-443d-a436-8847d341ce92
			defaultHierarchy: LocalDateTable_8d4ea7cb-356a-489a-b4fd-3ddb275dbfa7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: Short Date
		lineageTag: baa0e35c-94f3-42a7-8ece-a904bc1b4d5f
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: 6d20b27b-e95f-4d4c-8d44-278a28f9259a
			defaultHierarchy: LocalDateTable_1face99b-8823-4750-aa5d-e235b8078aa9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3e68a793-9223-4281-91f8-25e2eb9845ec
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 90d55876-8d44-4635-b67e-cb2e51716ae4
			defaultHierarchy: LocalDateTable_f335df94-90e5-46c0-8c6e-cf21da18565b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b4bf024-3fee-4eb7-b520-6345e36643d0
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 8ebee4ea-f5d7-4259-966a-227918978098
			defaultHierarchy: LocalDateTable_16b76d48-0742-43e7-95ca-cd6e008b7034.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2d256427-7f92-45c9-9514-2a1030cd6c34
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: 5bd7d06b-24d1-4f05-a75e-cda74925e852
			defaultHierarchy: LocalDateTable_070d540b-8374-468b-87e9-fa579643c016.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Order Status '
		dataType: string
		lineageTag: 00503291-9a8e-4b85-8e5c-c48b53fbbef5
		summarizeBy: none
		sourceColumn: "Order Status "

		annotation SummarizationSetBy = Automatic

	column Year = FORMAT(olist_orders_dataset[order_purchase_timestamp],"YYYY")
		lineageTag: cd64621b-2ca6-4381-9bfd-c42df7e56b77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column month = ```
			FORMAT(olist_orders_dataset[order_purchase_timestamp],"MMM") 
			```
		lineageTag: 47787f1d-76a1-45f6-8f33-d0dbdb250cb7
		summarizeBy: none
		sortByColumn: 'month number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'month number' = MONTH(olist_orders_dataset[order_purchase_timestamp])
		formatString: 0
		lineageTag: 89dd9fbb-9a8c-4a83-acf0-9fc3f604737e
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Order Date' =
			DATE(
			    YEAR(olist_orders_dataset[order_purchase_timestamp]),
			    MONTH(olist_orders_dataset[order_purchase_timestamp]),
			    DAY(olist_orders_dataset[order_purchase_timestamp])
			)
		formatString: General Date
		lineageTag: 202eb051-1d98-4515-b887-dda8639b6f82
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8f095b59-fc15-4533-afd4-7b40ea6a8885
			defaultHierarchy: LocalDateTable_e5aac855-19cd-42a0-a25e-66a1b0cf8f0a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition olist_orders_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\My office\archive\olist_orders_dataset.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"customer_id", type text}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"order_status", "order_status 1"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Order Status ", each if [order_status 1] = "delivered" then "completed"
				else if [order_status 1] = "canceled" then "canceled"
				else "In Progress")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

